/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#FAF7F2",
        "surface": "#FDFBF7",
        "surface-dim": "#EFECE6",
        "surface-bright": "#FAF7F2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#F7F4EE",
        "surface-container": "#EFECE6",
        "surface-container-high": "#E7E3DC",
        "surface-container-highest": "#DDD8CE",
        "on-surface": "#1F2421",
        "on-surface-variant": "#4B534D",
        "inverse-surface": "#29322D",
        "inverse-on-surface": "#FAF7F2",
        "outline": "#7E8881",
        "outline-variant": "#E7E3DC",
        "surface-tint": "#E05A47",
        "primary": "#E05A47",
        "on-primary": "#ffffff",
        "primary-container": "#E05A47",
        "on-primary-container": "#ffffff",
        "inverse-primary": "#FFB4A8",
        "secondary": "#4A7C59",
        "on-secondary": "#ffffff",
        "secondary-container": "#EDF4EF",
        "on-secondary-container": "#4A7C59",
        "tertiary": "#D99B4B",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#FDF5EB",
        "on-tertiary-container": "#B87B2E",
        "error": "#BA1A1A",
        "on-error": "#ffffff",
        "error-container": "#FFDAD6",
        "on-error-container": "#93000A",
        "primary-fixed": "#FFDAD4",
        "primary-fixed-dim": "#FFB4A8",
        "on-primary-fixed": "#410100",
        "on-primary-fixed-variant": "#8A1C10",
        "secondary-fixed": "#B9EFC5",
        "secondary-fixed-dim": "#9DD3AA",
        "on-secondary-fixed": "#00210E",
        "on-secondary-fixed-variant": "#1E5031",
        "tertiary-fixed": "#FFDDB8",
        "tertiary-fixed-dim": "#FCBA66",
        "on-tertiary-fixed": "#2A1700",
        "on-tertiary-fixed-variant": "#653E00",
        "on-background": "#1F2421",
        "surface-variant": "#EFECE6"
      },
      borderRadius: {
        "DEFAULT": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "space-xxs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "content-max-feed": "42rem",
        "content-max-reading": "48rem",
        "content-max-layout": "76rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "2rem"
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        editorial: ["'Newsreader'", "serif"]
      }
    },
  },
  plugins: [],
}

